### ISSUE TITLE
Rules not equal 

### ISSUE THREAD

**Issue by NielsDWG** [touchifyapp/vsts-changed-files#20]
Hi there!

First let me say that you created a nice plugin!
My question: I really would like to detect changes in every folder except a specified on. Is this possible?

So I want the variable to be false if there are no other changes other than, lets say, something in folder 'x', and the variable to be true if anything else is changed.

I do understand that I can add multiple filter rules, but there would be a lot in stead of one simple rule.

Thanks in advance!
Niels

**Comment by SomaticIT** [comment]
Hello,

I'm not sure it works with our implementation but I think you can do it if you use a single rule:

```yaml
- task: ChangedFiles@1
  name: CheckChanges
  inputs:
    rules: |
      [SkipFolderX]
      !x/**
```
