### ISSUE TITLE
Unexpected results while trying to exclude/include stages 

### ISSUE THREAD

**Issue by MykolaPelyp-SoftServe** [touchifyapp/vsts-changed-files#21]
Hi! 
1. Our stages:
build - - > wrap - - > deploy
2. our GOAL:
When we commit to special increment file (which is included in the trigger path _svc/changed.md_) we need to   trigger our pipe and only wrap&deploy stages should go through while skipping long build stage.
When we manually trigger pipeline or through other triggers we need all stages to get through **completely ignoring existence of preCheck stage**  

It does not work, for some reason Build stage does not recognise boolean in conditions we tried "ne == true OR eq == false" 
So, **main question**: is your extension support not equal e.g. condition=false?
PS. We had like 20 test runs with various parameters, presented code is last changed variant, in that variant all stages being skipped, either way the goal is to run build stage every time **except svc/changed.md being changed**
PSS. We ended up trying to use your extension because of Az pipelines limitation in API (unable to trigger particular stages) and unable to set up trigger for particular stage and unable to set conditions based on file to which we got commit...

```
      trigger:
        branches:
          include:
            - develop
        paths:
          include:
            - svc/changed.md
stages:
  - stage: preCheck
    jobs:
      - job: Changelog
        displayName: Check whether we ran auto deploy
        steps:
          - task: ChangedFiles@1
            name: CheckChanges
            inputs:
              refBranch: develop
              rules: |
                [Changed]
                svc/changed.md

  - stage: Build
    dependsOn: preCheck
    condition: ne(dependencies.check.outputs['CheckChanges.Changed'], 'true')

  - stage: wrap
  - stage: deploy

**Comment by MykolaPelyp-SoftServe** [comment]
This simple case should work or should not? Build stage runs either way, even if I commit to changelog.md

```
stages:
  - stage: preCheck
    jobs:
      - job: changed
        displayName: Check whether auto deploy
        steps:
          - task: ChangedFiles@1
            name: CheckChanges
            inputs:
              rules: changelog.md
              variable: changed
              
  - stage: Build
    dependsOn: preCheck
    condition: ne(dependencies.check.outputs['CheckChanges.changed'], 'true')
    
   ```

**Comment by MykolaPelyp-SoftServe** [comment]
Achieved this by standard az pipeline yaml but still, I think if you could tell why your extension did not work in my case it'll benefit for community...Including me of course
code that worked: (I think it still could have been accomplished easier/better by someone with better exp with Azure pipelines) 

```
parameters:
  - name: env
    displayName: Environment
    type: string
    default: default
    values:
      - default
      - dev
      - qa
  - name: pipeline_mode
    default: only_deploy
    values:
      - only_deploy
      - all_stages

pool:
  name: our-own-linux-ubuntu-pool

resources:
  repositories:
    - repository: <REDUCTED>
      name: <REDUCTED>
      type: git
      ref: feature/<REDUCTED>
      trigger:
        branches:
          include:
            - develop
            - feature/<REDUCTED>
        paths:
          include:
            - changelog.md

stages:
- stage: Build
  condition: eq('${{ parameters.pipeline_mode }}', 'all_stages')
  displayName: Build
  jobs:
    - job: Build
      steps:
      - script: echo running Build


- stage: package
  displayName: package
  condition: or(eq('${{ parameters.pipeline_mode }}', 'all_stages'), eq('${{ parameters.pipeline_mode }}', 'only_deploy'))
  dependsOn: Build
  jobs:
  - job: package
    steps:
    - script: echo running package


- stage: Deploy
  displayName: Deploy
  condition: or(eq('${{ parameters.pipeline_mode }}', 'all_stages'), eq('${{ parameters.pipeline_mode }}', 'only_deploy'))
  dependsOn: package
  jobs:
  - job: Deploy
    steps:
    - script: echo running deploy
 
```
