### ISSUE TITLE
Current branch changes with multiple repositories

### ISSUE THREAD

**Issue by EliiseS** [touchifyapp/vsts-changed-files#24]
If I have a pipeline, with multiple repos, the `current` branch will always be set to be to the repository with the `pipeline.yaml` file on manual trigger of the pipeline, not to the one used in the check out of job.

```yaml
# pipeline.yaml located in Foo repository
resources:
  repositories:
    - repository: Foo
      type: git
      name: Foo/Foo
    - repository: Moo
      type: git
      name: Moo/Moo
      trigger:
        branches:
          include: [development, release/*] # <--- On trigger, this may set the `current` branch to be the correct one, but we have not tested this

stages:
  - stage: Check
    jobs:
      - job: check
        displayName: Check changed files
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: Moo
          # "Current Branch: main/foo", despite the checkout on manual trigger
          - task: ChangedFiles@1
            name: CheckChanges
            inputs:
              refBranch: development
              verbose: true
              rules: |
                [SrcChanged]
                src/**/*

                [ImageChanged]
                image/**/*
```

Co-author: @desertmark
