### ISSUE TITLE
Doesn't work with stageDependencies

### ISSUE THREAD

**Issue by KristapsT** [touchifyapp/vsts-changed-files#29]
The output variable doesn't seem to work correctly when used in different stage with `stageDependencies`

My pipeline:
```
stages:
  - stage: pre
    jobs:
      - job: check
        displayName: Check changed files
        steps:
          - task: ChangedFiles@1
            name: Changes
            inputs:
              rules: changesHere/**
              variable: hasChanged
              verbose: true

      - job: jobWithCondition
        dependsOn:
          - check
        condition: eq(dependencies.check.outputs['Changes.hasChanged'], 'true')
        steps:
          - script: echo "run with condition"

  - stage: stageWithCondition
    dependsOn:
      - pre
    condition: eq(stageDependencies.pre.check.outputs['Changes.hasChanged'], 'true')
    jobs:
      - job: runThisOnCondition
        steps:
          - script: echo "run with condition"

  - stage: alwaysRun
    dependsOn:
      - pre
    variables:
      conditionIs: $[ eq(stageDependencies.pre.check.outputs['Changes.hasChanged'], 'true') ]
    jobs:
      - job: showValueOfCondition
        steps:
          - script: echo "conditionIs=$(conditionIs)"
```

Output from `check` job:
```
azure-pipelines.yml
changesHere/some_file.txtt
>> Changed files:
	 - azure-pipelines.yml
	 - changesHere/some_file.txtt
> Filtering files using glob rules
>> HASCHANGED: Changes detected since last succeeded build, setting "hasChanged" to "true"
```

Expected result: stage `stageWithCondition` runs and job `jobWithCondition` in stage `check` also runs

Actual result: stage `stageWithCondition` gets skipped. Job `jobWithCondition` in stage `check` works as expected.

Additionally, output from job `showValueOfCondition` in stage `alwaysRun` is `conditionIs=True`. This is probably the weirdest part. It shows that the variable actually gets set correctly...but not when evaluating the condition of stage.

**Comment by KristapsT** [comment]
To add more information - the condition works of it is moved job definition, instead of stage.

Like this:
```
stages:
  - stage: pre
    jobs:
      - job: check
        displayName: Check changed files
        steps:
          - task: ChangedFiles@1
            name: Changes
            inputs:
              rules: changesHere/**
              variable: hasChanged
              verbose: true

      - job: jobWithCondition
        dependsOn:
          - check
        condition: eq(dependencies.check.outputs['Changes.hasChanged'], 'true')
        steps:
          - script: echo "run with condition"

  - stage: stageWithCondition
    dependsOn:
      - pre
    jobs:
      - job: runThisOnCondition
        condition: eq(stageDependencies.pre.check.outputs['Changes.hasChanged'], 'true')
        steps:
          - script: echo "run with condition"

  - stage: alwaysRun
    dependsOn:
      - pre
    variables:
      conditionIs: $[ eq(stageDependencies.pre.check.outputs['Changes.hasChanged'], 'true') ]
    jobs:
      - job: showValueOfCondition
        steps:
          - script: echo "conditionIs=$(conditionIs)"
```

In this case all conditions work as expected.

This needs to be either clearly documented and the behavior for when condition is in stage definition fixed.

**Comment by wradstok** [comment]
I've also been experimenting with this, and I have gotten it to work. The trick is that when in a stage condition, variables are accessed in a different way. They are read from `dependencies.{stagename}.outputs['{jobname}.{variablename}`.

In the following example, I have two folders, named `foo` and `bar`. When any file in those the folder is changed, the corresponding stage runs a single job with a single task which prints that a change has occured 😄 

```
stages:
  - stage: pre
    jobs:
      - job: check
        displayName: Check changed files
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: ChangedFiles@1
            name: CheckChanges
            inputs:
              refBranch: main 
              rules: |
                [BarChanged]
                bar/**

                [FooChanged]
                foo/**
          - script: | 
              echo $(CheckChanges.BarChanged)
              echo $(CheckChanges.FooChanged)

  - stage: bar_has_changed
    dependsOn: ["pre"]
    condition: eq(dependencies.pre.outputs['check.CheckChanges.BarChanged'], 'true')
    jobs: 
      - job: run
        steps:
          - script: echo "bar has changed!"

  - stage: foo_has_changed
    dependsOn: ["pre"]
    condition: eq(dependencies.pre.check.outputs['check.CheckChanges.FooChanged'], 'true')
    jobs: 
      - job: run
        steps:
          - script: echo "foo has changed!"
```
