### ISSUE TITLE
Use with task scope

### ISSUE THREAD

**Issue by jnus** [touchifyapp/vsts-changed-files#37]
Hi - 

Should it not be possible to use the output variables for conditions on task level instead? When change a single file within the path of one of the filters, the output variables both renders true in the pwsh step and the conditions for the helm steps. Should this not be supported?

```
...
 - task: ChangedFiles@1
      name: CheckChanges
      inputs:
        rules: |
          [microservicesChanged]
          microservices/**/*.*
          [gatewaysChanged]
          /gateways/**/*.*
    
    - powershell: |
        write-host "microservicesChanged: $(CheckChanges.microservicesChanged) ..."
        write-host "gatewaysChanged: $(CheckChanges.gatewaysChanged) ..."
    
    - task: HelmDeploy@0
      condition: and(succeeded(), eq(variables['CheckChanges.microservicesChanged'], 'true'))
      displayName: Helm package microservices
      inputs:
        command: package
        chartPath: $(helmBasePath)/microservices
        destination: $(Build.ArtifactStagingDirectory)
        chartVersion: $(versionSha)

    - task: HelmDeploy@0  
      condition: and(succeeded(), eq(variables['CheckChanges.gatewaysChanged'], 'true')) 
      displayName: Helm package gateways
      inputs:
        command: package
        chartPath: $(helmBasePath)/gateways
        destination: $(Build.ArtifactStagingDirectory)
        chartVersion: $(versionSha)
...
```

**Comment by jnus** [comment]
So above syntax might be supported, but files changed seems off. Enabling system.debug, I see that when changing a single file in a branch, all files in the repo are marked as changed.  Any idea why this is?

**Comment by jnus** [comment]
Will just go ahead and answer my own question here for future readers. Refbranch need to be set, in order for the task to determine the changes correctly. I'm doing the following now. Note the refBranch cannot be the fully qualified name e.g. 'refs/heads/feature/awesomeStuff' specified in Build.SourceBranch, but only the branch name 'feature/awesomeStuff'. As this is not a default variable, I'm setting the variable 'branchName'. 

```
...
variables:
   branchName: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
...
 - task: ChangedFiles@1
      name: CheckChanges
      inputs:
        refBranch: $(branchName)
        rules: |
          [microservicesChanged]
          microservices/**/*.*
          [gatewaysChanged]
          /gateways/**/*.*
    
    - powershell: |
        write-host "microservicesChanged: $(CheckChanges.microservicesChanged) ..."
        write-host "gatewaysChanged: $(CheckChanges.gatewaysChanged) ..."
    
    - task: HelmDeploy@0
      condition: and(succeeded(), eq(variables['CheckChanges.microservicesChanged'], 'true'))
      displayName: Helm package microservices
      inputs:
        command: package
        chartPath: $(helmBasePath)/microservices
        destination: $(Build.ArtifactStagingDirectory)
        chartVersion: $(versionSha)

    - task: HelmDeploy@0  
      condition: and(succeeded(), eq(variables['CheckChanges.gatewaysChanged'], 'true')) 
      displayName: Helm package gateways
      inputs:
        command: package
        chartPath: $(helmBasePath)/gateways
        destination: $(Build.ArtifactStagingDirectory)
        chartVersion: $(versionSha)
```
